### ISSUE TITLE
为什么我总是报错404啊，可不可以给个联系方式啊

### ISSUE THREAD

**Issue by 1HABIT1** [aYIfseec/CMS#7]
index.html 不应该在WebRoot目录下吗
web.xml的路径我感觉有点不懂，想深入研究下，求速回，万分感激

**Comment by aYIfseec** [comment]
qq
754912298
你404的屏幕截图给我看看


 
---原始邮件---
发件人: "刘华"<notifications@github.com&gt;
发送时间: 2020年4月26日 12:35:35
收件人: "aYIfseec/CMS"<CMS@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [aYIfseec/CMS] 为什么我总是报错404啊，可不可以给个联系方式啊 (#7)




 
index.html 不应该在WebRoot目录下吗
 web.xml的路径我感觉有点不懂，想深入研究下，求速回，万分感激

**Comment by 1HABIT1** [comment]
抱歉啊，没想到你这么快就能回复，我加你QQ了，你这么快就能回复，我加你QQ了，这样能方便些
[我的错误.docx](https://github.com/aYIfseec/CMS/files/4549431/default.docx)

**Comment by 1HABIT1** [comment]
> index.html 不应该在WebRoot目录下吗 web.xml的路径我感觉有点不懂，想深入研究下，求速回，万分感激

**Comment by aYIfseec** [comment]
ToExperienceXYZ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月20日(星期天) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aYIfseec/CMS] 为什么我总是报错404啊，可不可以给个联系方式啊 (#7)





 
Closed #7.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aYIfseec** [comment]
微信




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月20日(星期天) 上午10:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aYIfseec/CMS] 为什么我总是报错404啊，可不可以给个联系方式啊 (#7)





 
Closed #7.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
